karim/karim/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('django/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shop.urls')),
    path('administration/', include('administration.urls'))
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

karim/main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    
    path('products/', product_list, name='products'),
    path('product/<slug:slug>/', product_detail, name='product'),
    path('like/product/<slug:slug>/', like_product, name='like'),

    path('categories/', CategoryListView.as_view(), name='categories'),
    path('category/<slug:slug>/', category_detail, name='category'),

    path('search/', search, name='search'),
]

karim/shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'
urlpatterns = [
    path('new/order/<int:product_pk>/', add_to_bucket, name='add_to_bucket'),
    path('remove/order/<int:order_pk>/', del_from_bucket, name='remove_order'),

    path('bucket/validate/', validate_order, name='validate_bucket'),
    path('buckets/list/', show_orders, name='show_buckets'),
    
    path('', bucket, name='bucket'),
]

karim/shop/models.py
from django.db import models
from main.models import Product


# Create your models here.
class Base(models.Model):

    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        ordering = ['-updated_at']


class Order(Base):

    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class Bucket(Base):

    name = models.CharField(max_length=150, default="")
    value = models.DecimalField(default=0, max_digits=7, decimal_places=2)
    validated = models.BooleanField(default=False)
    sent = models.BooleanField(default=False)
    order = models.ManyToManyField(Order, related_name='orders')

karim/shop/views.py
from django.shortcuts import render, get_object_or_404 as _g
from shop.models import Order, Bucket
from main.models import Product

from django.http import JsonResponse
from django.utils.text import slugify


# Create your views here.
def add_to_bucket(request, product_pk):
    
    # On ajoute la clé validated dans la session.
    request.session['validated'] = False

    
    product = _g(Product, pk=product_pk)

    order = Order(product=product)
    order.save()

    bucket = request.session['bucket']
    bucket.append(order.pk)

    request.session['bucket'] = bucket

    return JsonResponse({
        'message': "Votre commande a été ajoutée",
        "order_count": len(request.session['bucket'])
    })

def del_from_bucket(request, order_pk):
    
    order = _g(Order, pk=order_pk)
    
    bucket = request.session['bucket']
    bucket.remove(order_pk)

    request.session['bucket'] = bucket
    
    order.delete()

    request.session['validated'] = False

    return JsonResponse({
        'message': "La commande a été supprimée"
    })

def validate_order(request):
    
    context = {}

    try:

        # Si la session existe.
        if request.session['bucket'] and len(request.session['bucket'])!= 0 and not request.session['validated']:
            
            # On regroupe toutes les commandes dans un panier.
            bucket = Bucket()
            bucket.sent = True
            bucket.save()

            total_price = 0

            for order in request.session['bucket']:
                _order = _g(Order, pk=order)
                bucket.order.add(_order)

                total_price += _order.product.price
            
            bucket.value = total_price
            bucket.save()

            # On ajoute la clé validated dans la session.
            request.session['validated'] = True

            # On vide le panier.
            del request.session['bucket']

            context['message'] = "Votre commande a été enregistrée, nous reviendrons vers vous pour entamer la démarche nécessaire"
    
    except:
        
        # On va afficher un message d' erreur.
        context['message'] = "Une erreur s'est produite lors de la validation de votre commande"

    return JsonResponse(context)

def bucket(request):
    
    context = {}

    try:

        bucket = [_g(Order, pk=pk) for pk in request.session['bucket']]
        context['bucket'] = bucket
        context['total_price'] = sum([x.product.price for x in bucket]) if len(bucket) > 0 else 0
    
    except:

        request.session['bucket'] = []

    return render(request, "bucket.html", context)


# Validation de la commande par l'administrateur
import accounts.views.decorators as decorators
import django.contrib.auth.decorators as auth

@auth.user_passes_test(decorators.user_is_admin)
def show_orders(request):

    context = {}

    buckets = Bucket.objects.filter(validated=False, sent=True)
    context['buckets'] = buckets
    context['total_buckets'] = buckets.count()

    return render(request, "show_buckets.html", context)

karim/shop/templates/bucket.html
{% extends "layout.html" %}

{% block main %}

<div class="container">

    <h1 class="uk-text-center my-title">Votre panier</h1>

    <div class=" uk-margin-large-top">

        <p>
            <a id="validate" onclick="validate()" href="#" class="uk-button uk-button-success">Passer toutes les commandes: {{ total_price }} €</a>
        </p>

        {% for order in bucket %}

        <div class="uk-card uk-card-default uk-child-width-1-1@s uk-grid-collapse uk-margin" uk-grid>

            <div class="uk-width-1-3@m uk-card-media-left uk-cover-container">
                <img src="{{ order.product.image.url }}" alt="{{ order.product.name }}" uk-cover/>
                <canvas width="150" height="150"></canvas>
            </div>
            <div class="uk-width-2-3@m">
                <div class="uk-card-body uk-padding">
                    <div class="row col-12">

                        <div class="col-3">
                            <p class="uk-text-meta">
                                Commande n°
                                {{ order.pk }}
                            </p>
                        </div>

                        <div class="col-4">
                            <a class="uk-text-meta" href="{{ order.product.get_absolute_url }}">
                                {{ order.product.name}}
                            </a>
                        </div>

                        <div class="col-5">
                            <p class="uk-text-meta">
                                Commandé le {{ order.created_at }}
                            </p>
                        </div>

                    </div>
                    <div class="row col-12">
                        <div class="col-12">
                            <a onclick="deleteOrder({{order.pk}})" href="#" class="del_from_bucket col-12 uk-button uk-button-danger">Supprimer du panier</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <p class="uk-text-center uk-text-lead">
            Vous n'avez aucune commande dans votre panier
        </p>
        {% endfor %}

    </div>


</div>

{% endblock main %}

{% block script %}
<script>

    $('.del_from_bucket').click(e => {
        e.preventDefault()
    })


    const deleteOrder = (id) => {
        $.ajax({
            url: `remove/order/${id}/`,
            success: data => {
                UIkit.notification({
                    message: "Votre commande a été annulée",
                    status: "primary",
                    timeout: 2000
                })
            },
            error: error => {
                UIkit.notification({
                    message: "Impossible d'annuler votre commande",
                    status: "danger ",
                    timeout: 2000
                })
            }
        })
    }

    const validate = () => {
        $.ajax({
            url: "{% url 'shop:validate_bucket' %}",
            success: data => {
                $('.container').load("{% url 'shop:bucket' %}")
            },
            error: error => {

            }
        })
    }

</script>
{% endblock script %}

karim/shop/templates/show_buckets.html
{% extends "layout.html" %}

{% block title %}

{% endblock title %}

{% block main %}

<div>

    <h1 class="my-title uk-text-center">Liste des commandes</h1>

    <p>
        <span class="uk-label">Note</span>
        Vous avez {{ total_buckets }} commandes
    </p>

    <div class="uk-child-width-1-2@m uk-child-width-1-1@s" uk-grid>
        {% for bucket in buckets %}

        <div>

            <div class="uk-card uk-card-secondary uk-padding">
                <h3 class="uk-card-title">Commande n° {{ bucket.pk }}</h3>
                <ul>
                    <li class="uk-text-meta">Valeur de la commande: {{ bucket.value }} €</li>
                    <li class="uk-text-meta">Ajoutée le {{ bucket.created_at }}</li>
                </ul>
                <div class="row">
                    <a href="" class="col-md-6 col-sm-12 uk-button uk-button-primary">Validez la commande</a>
                    <a href="" class="col-md-6 col-sm-12 uk-button uk-button-danger">Refusez la commande</a>  
                </div>
                
            </div>

        </div>
        
        {% endfor %}
    </div>

</div>

{% endblock main %}