karim/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signin/', signin, name='login'),
    path('signup/', signup, name="signup"),
    path('signout/', signout, name='signout'),

    path('edit/firstname/', change_first_name, name='change_first_name'),
    path('edit/lastname/', change_last_name, name='change_last_name'),

    path('edit/', edit_profil, name='edit_profil'),
    path('delete/', delete_account, name='delete_profil'),
    path('profil/', view_profil, name='view_profil'),
]

karim/karim/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('django/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shop.urls')),
    path('administration/', include('administration.urls'))
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

karim/main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    
    path('products/', product_list, name='products'),
    path('product/<slug:slug>/', product_detail, name='product'),
    path('like/product/<slug:slug>/', like_product, name='like'),

    path('categories/', CategoryListView.as_view(), name='categories'),
    path('category/<slug:slug>/', category_detail, name='category'),

    path('search/', search, name='search'),
]

karim/templates/general/footer.html
<div class="container uk-child-width-1-3@m uk-child-width-1-1@s uk-flex-center uk-margin uk-margin-remove-bottom uk-padding" uk-grid>

    <div>
        <div>

            <h3 class="uk-h3" style="font-family: 'Pacifico'; color: white">
                Karim vente
            </h3>

            <p class="uk-text-meta">
                Nous vous proposons des produits de qualité, à des prix 
                raisonnables et totalement remboursables.
            </p>

        </div>
    </div>

    <div>
        <div>
            <h3 class="uk-h3" style="font-family: 'Pacifico'; color: white">Nos partenaires</h3>
            <ul>
                <li><a href="">Maestro Food</a></li>
            </ul>
        </div>
    </div>

    <div>
        <div>

            <h3 class="uk-h3" style="font-family: 'Pacifico'; color: white">Contactez-nous</h3>

            <p class="uk-text-meta">
                Pour toute information, veuillez contacter 
                le service client qui pourra répondre à vos questions.

                <span class="form-control uk-padding mt-2">
                    +33 6 16 55 29 34
                </span>
            </p>

            <a href="#" uk-totop uk-scroll class="btn btn-dark">Haut de la page</a>

        </div>
    </div>

</div>

karim/templates/general/header.html
{% include "general/navbar-md.html" %}
{% include "general/navbar-sm.html" %}

karim/templates/general/navbar-md.html
<div class="uk-visible@s" uk-sticky="sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky; bottom: #transparent-sticky-navbar">
    <nav class="uk-navbar-container" uk-navbar style="position: relative; z-index: 980;">

        <div class="uk-navbar-left uk-margin-medium-left">
            <ul class="uk-navbar-nav">
                <li><a href="{% url 'main:home' %}">Accueil</a></li>
                <li><a href="">Contact</a></li>
            </ul>
        </div>

        <div class="uk-navbar-center">

            <ul class="uk-navbar-nav">

                <li><a href={% url 'main:products' %}>Nos produits</a></li>

                <li><a href="{% url 'main:categories' %}">Catégories</a></li>
                    
                {% if not user.is_authenticated %}
                    <li>
                        <a href="{% url 'accounts:login' %}">Connectez-vous</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:signup' %}">Créer un compte</a>
                    </li>
                {% endif %}

            </ul>

        </div>

        {% include "forms/search.html" %}

    </nav>
</div>

karim/templates/general/navbar-sm.html
<div class="uk-offcanvas-content uk-hidden@s">
  
    <div class="uk-navbar-left">
        <a class="uk-navbar-toggle" uk-toggle="target: #offcanvas-nav-primary" uk-navbar-toggle-icon href="#"></a>
     </div>

    <div id="offcanvas-nav-primary" uk-offcanvas="mode: reveal; overlay: true">
        <div class="uk-offcanvas-bar uk-flex uk-flex-column">

            {% include "forms/search.html" %}
    
            <ul class="uk-nav uk-nav-default">
                <li class="uk-active"><a href="{% url 'main:home' %}">Accueil</a></li>
                
                <li class="uk-nav-header">Nos services</li>
                <li><a href="{% url 'main:products' %}"><span class="uk-margin-small-right" uk-icon="icon: thumbnails"></span> Nos produits</a></li>
                <li><a href="{% url 'main:categories' %}"><span class="uk-margin-small-right" uk-icon="icon: table"></span> Catégories</a></li>
                
                <li class="uk-nav-header">Authentification</li>
                <li><a href="{% url 'accounts:login' %}"><span class="uk-margin-small-right" uk-icon="icon: user"></span> Accès à votre compte</a></li>
                <li><a href="{% url 'accounts:signup' %}"><span class="uk-margin-small-right" uk-icon="icon: user"></span> Nouveau compte</a></li>
                
                <li class="uk-nav-header">Contact</li>
                <li><a href="#"><span class="uk-margin-small-right" uk-icon="icon: mail"></span> Service client</a></li>
            </ul>
    
        </div>
    </div>
</div>