karim/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signin/', signin, name='login'),
    path('signup/', signup, name="signup"),
    path('signout/', signout, name='signout'),

    path('edit/firstname/', change_first_name, name='change_first_name'),
    path('edit/lastname/', change_last_name, name='change_last_name'),

    path('edit/', edit_profil, name='edit_profil'),
    path('delete/', delete_account, name='delete_profil'),
    path('profil/', view_profil, name='view_profil'),
]

karim/karim/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('django/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shop.urls')),
    path('administration/', include('administration.urls'))
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

karim/main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    
    path('products/', product_list, name='products'),
    path('product/<slug:slug>/', product_detail, name='product'),
    path('like/product/<slug:slug>/', like_product, name='like'),

    path('categories/', CategoryListView.as_view(), name='categories'),
    path('category/<slug:slug>/', category_detail, name='category'),

    path('search/', search, name='search'),
]

karim/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse


# Create your models here.
class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    avatar = models.ImageField(upload_to='users')

    def __str__(self):
        return self.user.username
    
    def get_absolute_url(self):
        return reverse('accounts:view_profil')

karim/accounts/forms/EditProfile.py
from django import forms
from accounts.models import Profile
from django.contrib.auth.models import User

class EditUserForm(forms.Form):
    
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'uk-input uk-width-1-1',
        'placeholder': 'Ex: Malik'
    }), required=False)

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'uk-input uk-width-1-1',
        'placeholder': 'Ex: Ftissi'
    }), required=False)

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'uk-input uk-width-1-1',
        'placeholder': 'Ex: malik.ftissi@mail.com'
    }), required=False)



class EditProfileForm(forms.ModelForm):

    error_css_class = 'uk-form-error'
    required_css_class = 'uk-form-error'

    class Meta:
        model = Profile
        fields = '__all__'

karim/accounts/forms/LoginForm.py
from django import forms


class LoginForm(forms.Form):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'uk-input uk-width-1-1',
        'placeholder': "Ex: alpha22"
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'uk-input uk-width-1-1',
        'placeholder': 'Ex: warrior-fan164'
    }))

karim/accounts/forms/SignupForm.py
from django import forms
from django.contrib.auth.models import User
from accounts.models import Profile


class SignupForm(forms.Form):

    error_css_class = 'uk-form-error'
    required_css_class = 'uk-form-error'

    auto_id = True

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'uk-input uk-width-1-1',
        'placeholder': "Ex: alpha22"
    }), error_messages={
        'required': "Veuillez entrer un nom d'utilisateur"
    })

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'uk-input uk-width-1-1',
        'placeholder': "Ex: alpha22@gmail.com"
    }), error_messages={
        'required': "Veuillez entrer une adresse email"
    })

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'uk-input uk-width-1-1',
        'placeholder': "Ex: warrior-fan164"
    }), error_messages={
        'required': "Veuillez entrer un mot de passe"
    })

    rptpassword = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'uk-input uk-width-1-1',
        'placeholder': "Ex: warrior-fan164"
    }), error_messages={
        'required': "Vos mots de passe doivent correspondre"
    })

    def clean(self):
        
        cleaned_data = super().clean()

        username, email = cleaned_data['username'], cleaned_data['email']
        password, rptpassword = cleaned_data['password'], cleaned_data['rptpassword']

        if password != rptpassword:
            raise forms.ValidationError("Les deux mots de passe doivent être identiques")
        
        else:
            
            # On enregistre un nouvel utilisateur
            user = User.objects.create_user(username=username, email=email, password=password)
            user.save()

            # On crée son profil.
            profil = Profile(user=user, avatar='default.jpg')
            profil.save()
        
        return cleaned_data

karim/accounts/views/decorators.py
# Fonction qui va restreindre l'accès aux utilisateurs
# déjà connectés.

def user_not_authenticated(user):
    return not user.is_authenticated

def user_is_authenticated(user):
    return user.is_authenticated

def user_is_admin(user):
    return user.is_staff or user.superuser

karim/accounts/views/logout.py
from django.contrib.auth.decorators import user_passes_test
from .decorators import user_is_authenticated
from django.contrib.auth import logout
from django.shortcuts import redirect, reverse


@user_passes_test(user_is_authenticated)
def signout(request):
    logout(request)
    
    return redirect(reverse('main:home'))

karim/accounts/views/signin.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate as auth, login
from accounts.forms import LoginForm

from django.contrib.auth.decorators import user_passes_test
from .decorators import user_not_authenticated


@user_passes_test(user_not_authenticated, login_url='/', redirect_field_name=None)
def signin(request):

    context = {}

    form = LoginForm(request.POST or None)
    context['form'] = form

    if form.is_valid():
        
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']

        user = auth(request, username=username, password=password)
        
        if user:
            login(request, user)

            return redirect(reverse('main:home'))

    return render(request, "login.html", context)

karim/accounts/views/signup.py
from django.shortcuts import render, redirect, reverse
from accounts.forms import SignupForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import user_passes_test
from .decorators import user_not_authenticated


@user_passes_test(user_not_authenticated, login_url='/', redirect_field_name=None)
def signup(request):

    context = {}

    form = SignupForm(request.POST or None)
    context['form'] = form

    if form.is_valid():
        
        # On connecte l'utilisateur
        user = authenticate(request,\
            username=form.cleaned_data['username'], \
            password=form.cleaned_data['password'])
        
        if user:
            login(request, user)

            return redirect(reverse('main:home'))

    return render(request, "signup.html", context)

karim/accounts/templates/edit_profil.html
{% extends "layout.html" %}

{% block title %}
Edition du profil
{% endblock title %}

{% block main %}

<div class="container">

    <h2>Paramètres</h2>


    <form id="edit-profil-form" method="post"  enctype="multipart/form-data">
        {% csrf_token %}

        <fieldset class="uk-fieldset">

            <legend class="uk-legend">Compte</legend>

            <div class="uk-margin uk-child-width-1-2@m uk-child-width-1-1@s uk-flex-center" uk-grid>
                <div>
                    <div class="form-group">
                        <label class="label" for="">Entrez votre prénom</label>
                        {{ user_form.first_name }}
                    </div>
                </div>
                <div>
                    <div class="form-group">
                        <label class="label" for="">Entrez votre nom</label>
                        {{ user_form.last_name }}
                    </div>
                </div>

            </div>

            <div class="form-group uk-margin">
                <label class="label" for="">Entrez votre adresse email</label>
                {{ user_form.email }}
            </div>

            <div class="form-group uk-margin">
                <label class="label" for="">Image de profil</label><br>
                <div uk-form-custom>
                    {{ profil_form.avatar }}
                    <button class="uk-button uk-button-default" type="button" tabindex="-1">Choisissez une image</button>
                </div>
            </div>

            <div class="form-group uk-margin">
                <input id="submit" type="submit" class="uk-button uk-button-default" value="Enregistrer les modifications" />
                <a href="#modal" uk-toggle href="#" class="uk-button uk-button-danger">Désactiver mon compte</a>
            </div>

        </fieldset>
    </form>

</div>

<div id="modal" uk-modal>
    <div class="uk-modal-dialog uk-modal-body uk-padding">
        <button class="uk-modal-close-default" type="button" uk-close></button>
        <h2 class="uk-modal-title">Désactivation de votre compte</h2>
        <p class="uk-padding">
            En continuant, votre compte sera désactivé et pas supprimé pour des raisons de cohérence dans notre base de donnée.
            Vous n'aurez plus accès à celui-ci à moins de faire une demande de réactivation.
        </p>
        <p class="uk-text-right">
            <button class="uk-button uk-button-default uk-modal-close" type="button">Annuler</button>
            <button id="delete-link" class="uk-button uk-button-danger" type="button">Désactiver</button>
        </p>
    </div>
</div>

{% endblock main %}

{% block script %}

<script>
    $('#delete-link').click(e => {
        e.preventDefault()

        $.ajax({
            url: "{% url 'accounts:delete_profil' %}",
            success: data => {
                UIkit.notification({
                    message: "Votre compte a été bien modifié",
                    timeout: 2000,
                    status: "primary"
                })
            },
            error: error => {
                UIkit.notification({
                    message: "Une erreur s'est produite lors de la modification de votre compte",
                    timeout: 2000,
                    status: "error"
                })
            }
        })
        
    })
</script>

{% endblock script %}

karim/accounts/templates/login.html
{% extends "layout.html" %}

{% block main %}


<div class="container">

    <form action="" method="post" class="uk-panel uk-padding">

        {% csrf_token %}

        <fieldset class="uk-fieldset">

            <legend class="uk-legend">Connexion</legend>

            <div class="uk-margin">

                <label class="label" for="">Entrez votre nom d'utilisateur</label>
                
                <div>
                    <div class="uk-width-1-1 uk-inline">
                        <span class="uk-form-icon" uk-icon="icon:user"></span>
                        {{ form.username }}
                    </div>
                </div>
            </div>

            <div class="uk-margin">

                <label class="label" for="">Entrez votre mot de passe</label>
                <div>
                    <div class="uk-width-1-1 uk-inline">
                         <span class="uk-form-icon" uk-icon="icon:lock"></span>
                        {{ form.password }}
                    </div>
                </div>
        
            </div>

            <div class="form-group">
                <input type="submit" value="Se connecter" class="uk-button uk-button-secondary">
            </div>
        
        </fieldset>

    </form>

    <p class="uk-text-meta">
        Vous n'avez pas encore de compte ?
        <a href="{% url 'accounts:signup' %}">Créer un compte dès maintenant</a>
    </p>

</div>

{% endblock main %}

karim/accounts/templates/signup.html
{% extends "layout.html" %}


{% block main %}


<div class="container">

    <form action="#" method="post" class="uk-panel uk-padding">

        {% csrf_token %}

        {% if form.errors %}
            <div>
                {% for error in form.errors.values %}
                    <p class="uk-alert uk-alert-danger">
                        
                    </p>
                {% endfor %}
            </div>
        {% endif %}

        <fieldset class="uk-fieldset">

            <legend class="uk-legend">Nouveau compte</legend>

            <div id="step-1">

                <div class="uk-margin">

                    <label class="label" for="">Entrez votre nom d'utilisateur</label>
                    
                    <div>
                        <div class="uk-width-1-1 uk-inline">
                            <span class="uk-form-icon" uk-icon="icon:user"></span>
                            {{ form.username }}
                        </div>
                    </div>
                </div>

                <div class="uk-margin">

                    <label class="label" for="">Entrez votre adresse email</label>
                    <div>
                        <div class="uk-width-1-1 uk-inline">
                            <span class="uk-form-icon" uk-icon="icon: mail"></span>
                            {{ form.email }}
                        </div>
                    </div>
                
                </div>


                <div class="form-group">
                    <input id="continue" type="button" value="Continuer" class="uk-button uk-button-secondary">
                </div>

            </div>

            <div id="step-2" uk-hidden>
                <div class="uk-margin">

                    <label class="label" for="">Entrez votre mot de passe</label>
                    <div>
                        <div class="uk-width-1-1 uk-inline">
                            <span class="uk-form-icon" uk-icon="icon:lock"></span>
                            {{ form.password }}
                        </div>
                    </div>
            
                </div>

                <div class="uk-margin">

                        <label class="label" for="">Repetez votre mot de passe</label>
                        <div>
                            <div class="uk-width-1-1 uk-inline">
                                <span class="uk-form-icon" uk-icon="icon:lock"></span>
                                {{ form.rptpassword }}
                            </div>
                        </div>
                
                    </div>

                <div class="form-group">
                    <input type="submit" value="Se connecter" class="uk-button uk-button-secondary">
                </div>

            </div>
        
        </fieldset>

    </form>

    <p class="uk-text-meta">
        Vous avez déjà un compte ?
        <a href="{% url 'accounts:login' %}">Connectez-vous alors !</a>
    </p>

</div>

{% endblock main %}

{% block script %}

<script>

    // La deuxième partie du formulaire est cachée par défaut.
    $('#step-2').hide()

    $('#continue').click(e => {
        $('#continue').fadeOut(200, () => {
            $('#step-2').fadeIn(300)
        })
    })

</script>


{% endblock script %}

karim/accounts/templates/view_profil.html
{% extends "layout.html" %}

{% block title %}
{{ user.username }}
{% endblock title %}

{% block main %}

<div>

    {% include "profil/profil_resume.html" %}


</div>

{% endblock main %}

{% block script %}
<script>

    $('#change_first_name').click(e => {
        e.preventDefault()

        $.ajax({
            url: `{% url 'accounts:change_first_name' %}?first_name=${$('#first_name').val()}`,
            success: data => {
                $('#first_name').text(data.first_name)
            },
            error: error => {
                $('#change_first_name').removeClass('is-info')
                $('#change_first_name').addClass('is-warning')
            }
        })
    })

    $('#change_last_name').click(e => {
        e.preventDefault()

        $.ajax({
            url: `{% url 'accounts:change_last_name' %}?last_name=${$('#last_name').val()}`,
            success: data => {
                $('#last_name').text(data.last_name)
            },
            error: error => {
                $('#change_last_name').removeClass('is-info')
                $('#change_last_name').addClass('is-warning')
            }
        })
    })

</script>
{% endblock script %}