karim/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signin/', signin, name='login'),
    path('signup/', signup, name="signup"),
    path('signout/', signout, name='signout'),

    path('edit/firstname/', change_first_name, name='change_first_name'),
    path('edit/lastname/', change_last_name, name='change_last_name'),

    path('edit/', edit_profil, name='edit_profil'),
    path('delete/', delete_account, name='delete_profil'),
    path('profil/', view_profil, name='view_profil'),
]

karim/administration/urls.py
from django.urls import path, include
from .views import *

app_name = 'administration'
urlpatterns = [
    path('', adminhome, name='adminhome'),
    path('add/product/', add_product, name='add_product'),
]

karim/karim/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('django/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shop.urls')),
    path('administration/', include('administration.urls'))
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

karim/main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    
    path('products/', product_list, name='products'),
    path('product/<slug:slug>/', product_detail, name='product'),
    path('like/product/<slug:slug>/', like_product, name='like'),

    path('categories/', CategoryListView.as_view(), name='categories'),
    path('category/<slug:slug>/', category_detail, name='category'),

    path('search/', search, name='search'),
]

karim/shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'
urlpatterns = [
    path('new/order/<int:product_pk>/', add_to_bucket, name='add_to_bucket'),
    path('remove/order/<int:order_pk>/', del_from_bucket, name='remove_order'),

    path('bucket/validate/', validate_order, name='validate_bucket'),
    path('buckets/list/', show_orders, name='show_buckets'),
    
    path('', bucket, name='bucket'),
]

karim/accounts/forms/EditProfile.py
from django import forms
from accounts.models import Profile
from django.contrib.auth.models import User

class EditUserForm(forms.Form):
    
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'uk-input uk-width-1-1',
        'placeholder': 'Ex: Malik'
    }), required=False)

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'uk-input uk-width-1-1',
        'placeholder': 'Ex: Ftissi'
    }), required=False)

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'uk-input uk-width-1-1',
        'placeholder': 'Ex: malik.ftissi@mail.com'
    }), required=False)



class EditProfileForm(forms.ModelForm):

    error_css_class = 'uk-form-error'
    required_css_class = 'uk-form-error'

    class Meta:
        model = Profile
        fields = '__all__'

karim/accounts/forms/LoginForm.py
from django import forms


class LoginForm(forms.Form):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'uk-input uk-width-1-1',
        'placeholder': "Ex: alpha22"
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'uk-input uk-width-1-1',
        'placeholder': 'Ex: warrior-fan164'
    }))

karim/accounts/forms/SignupForm.py
from django import forms
from django.contrib.auth.models import User
from accounts.models import Profile


class SignupForm(forms.Form):

    error_css_class = 'uk-form-error'
    required_css_class = 'uk-form-error'

    auto_id = True

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'uk-input uk-width-1-1',
        'placeholder': "Ex: alpha22"
    }), error_messages={
        'required': "Veuillez entrer un nom d'utilisateur"
    })

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'uk-input uk-width-1-1',
        'placeholder': "Ex: alpha22@gmail.com"
    }), error_messages={
        'required': "Veuillez entrer une adresse email"
    })

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'uk-input uk-width-1-1',
        'placeholder': "Ex: warrior-fan164"
    }), error_messages={
        'required': "Veuillez entrer un mot de passe"
    })

    rptpassword = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'uk-input uk-width-1-1',
        'placeholder': "Ex: warrior-fan164"
    }), error_messages={
        'required': "Vos mots de passe doivent correspondre"
    })

    def clean(self):
        
        cleaned_data = super().clean()

        username, email = cleaned_data['username'], cleaned_data['email']
        password, rptpassword = cleaned_data['password'], cleaned_data['rptpassword']

        if password != rptpassword:
            raise forms.ValidationError("Les deux mots de passe doivent être identiques")
        
        else:
            
            # On enregistre un nouvel utilisateur
            user = User.objects.create_user(username=username, email=email, password=password)
            user.save()

            # On crée son profil.
            profil = Profile(user=user, avatar='default.jpg')
            profil.save()
        
        return cleaned_data

karim/main/views/search.py
from django.shortcuts import render
from main.models import Product, Category


def search(request):

    question = request.GET['q']

    context = {}

    categories = Category.objects.filter(name__icontains=question)
    products = Product.objects.filter(name__icontains=question)

    context['categories'] = categories
    context['products'] = products


    return render(request, 'forms/search_results.html', context)

karim/templates/forms/search.html
<div class="nav-overlay uk-navbar-right">
    <ul class="uk-navbar-nav">
        <li>
            <a class="uk-navbar-toggle" uk-search-icon uk-toggle href="#modal-full"></a>
        </li>
        <li>
            <a href="{% url 'shop:bucket' %}">
                <span uk-icon="icon: cart "></span>
                <span class="uk-badge" id="shop-count">{{ shop_count }}</span>
            </a>
        </li>
        {% if user.is_authenticated %}
        
        <li>
            <a href=""><span uk-icon="icon: user"></span></a>
            <div uk-dropdown="pos: left-bottom">
                <ul class="uk-nav uk-dropdown-nav">
                    <li class="uk-nav-header">Mon compte</li>
                    <li><a href="{% url 'accounts:view_profil' %}">Voir mon profil</a></li>
                    <li><a href="{% url 'accounts:edit_profil' %}">Paramètres</a></li>
                    <li class="uk-nav-divider"></li>
                    {% if user.is_staff %}
                    <li class="uk-nav-header">Administration</li>
                    <li><a href="{% url 'administration:adminhome' %}">Gérer les produits</a></li>
                    <li><a href="{% url 'shop:show_buckets' %}">Gérer les commandes</a></li>
                    {% endif %}
                    <li><a href="{% url 'accounts:signout' %}">Déconnexion</a></li>
                </ul>
            </div>
        </li>
        
        {% endif %}
    </ul>
</div>

<div id="modal-full" class="uk-modal-full uk-modal" uk-modal>
    <div class="uk-modal-dialog uk-flex uk-flex-center uk-flex-middle" uk-height-viewport>
        <button class="uk-modal-close-full" type="button" uk-close></button>
        <form action="{% url 'main:search' %}" class="uk-search uk-search-large">
            <input class="uk-search-input uk-text-center" name="q" type="search" placeholder="Rechercher..." autofocus>
        </form>
    </div>
</div>

karim/templates/forms/search_results.html
{% extends "layout.html" %}

{% block title %}

{% endblock title %}

{% block main %}

<div>

    <div uk-grid="masonry: true">
        {% for category in categories %}

            <div>
        
                <div class="uk-tile uk-tile-secondary uk-padding">

                    <a class="" href="{{ category.get_absolute_url }}">{{ category.name }}</a>

                </div>

            </div>

        {% empty %}
            <div class="uk-width-1-1">
                <div>
                    <p class="uk-alert uk-alert-primary">
                        Aucune catégorie ne correspond à votre recherche
                    </p>
                </div>
            </div>
        {% endfor %}
    </div>

    <div uk-grid uk-scrollspy="cls: uk-animation-fade; target: > div > .uk-card; delay: 100; repeat: true">
    {% for product in products %}
        <div class="uk-margin">
            <div class="uk-tile uk-tile-muted uk-inline">

                <img src="{{ product.image.url }}" alt="" />
                <div class="uk-overlay uk-overlay-primary uk-position-bottom uk-flex uk-flex-between">
                    <div>{{ product.name }}</div>
                    <div>
                        <a href="{{ product.get_absolute_url }}">Voir le produit</a>
                    </div>
                </div>

            </div>
        </div>

    {% empty %}
        <div class="uk-width-1-1">
            <div class="uk-alert uk-alert-primary">Aucun produit ne correspond à votre recherce</div>
        </div>
    {% endfor %}
</div>

</div>

{% endblock main %}